In [34]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [35]:
env = gym.make("FrozenLake-v0")

In [36]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [41]:
rewards_all_episodes = []
# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params
    state = env.reset()

    #done to abalyze whether the episode is finished or not
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
          action = np.argmax(q_table[state, :])
        else :
          action = env.action_space.sample()

        # Take new action
        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        # Set new state
        state = new_state
    
        # Add new reward
        rewards_current_episode += reward

        if done == True:
          break
        

    # Exploration rate decay 
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)
  

In [42]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.04900000000000004
2000 :  0.22400000000000017
3000 :  0.4140000000000003
4000 :  0.5730000000000004
5000 :  0.6370000000000005
6000 :  0.6440000000000005
7000 :  0.6610000000000005
8000 :  0.6570000000000005
9000 :  0.6730000000000005
10000 :  0.6820000000000005


In [43]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.51538254 0.51473006 0.5158112  0.50987906]
 [0.27348508 0.35149986 0.39493217 0.49438336]
 [0.41059241 0.38518884 0.39473608 0.4661929 ]
 [0.31608565 0.40165061 0.27945108 0.44960827]
 [0.52304606 0.34433943 0.45116043 0.3963694 ]
 [0.         0.         0.         0.        ]
 [0.30469951 0.10409796 0.21665121 0.07709121]
 [0.         0.         0.         0.        ]
 [0.45140918 0.52924011 0.30195153 0.54531047]
 [0.50167405 0.57744216 0.29879157 0.34701761]
 [0.50709171 0.24873372 0.31015732 0.45772902]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.41779571 0.45055715 0.69448629 0.52700539]
 [0.71586913 0.82723565 0.72575295 0.72695704]
 [0.         0.         0.         0.        ]]


In [47]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table
score = 0 
for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        # Choose action with highest Q-value for current state
        action = np.argmax(q_table[state,:])       
        # Take new action
        new_state, reward, done, info = env.step(action)

        if done:
          clear_output(wait=True)
          env.render()
          if reward == 1:
              score += 1
              print("****You reached the goal!****")
              time.sleep(3)
          else:
              print("****You fell through a hole!****")
              time.sleep(3)
              clear_output(wait=True)
          break            

        # Set new state
        state = new_state

env.close()
print("Your score is : ",score,"/ 3")

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
Your score is :  2 / 3
